### ISSUE TITLE
In the "Chuck's boat" minigame the weapon blinks in the left corner of the screen

### ISSUE THREAD

**Issue by panchenko9b** [SuiMachine/Deadly-Premonition-2---Sui-s-hack#14]
I am using the default settings of your mod.

https://youtu.be/KniE2z4ItNw

**Comment by SuiMachine** [comment]
Weird, cause I purposefully added a section of the code that should prevent interpolating movement of camera and boat altogether in those sections (cause it's better to have them be updated 50 times a second, than glitch out like this). Do you have a save file?

**Comment by SuiMachine** [comment]
OK, so it seems the side activity has entirely different setup then the one used in main story. I have figured out a way to get interpolation disabled for that section as well to keep it a bit cleaner (even if the camera movement is jittery, due to 50 Hz updates). Also I think I have managed to find an issue that was causing geometry checker to break and throw an error, which is the main thing keeping 1.1.0 from proper release

**Comment by panchenko9b** [comment]
Fixed now. Thank you!
