### ISSUE TITLE
Ambient occlusion

### ISSUE THREAD

**Issue by filipthebest** [SuiMachine/Deadly-Premonition-2---Sui-s-hack#2]
Would it be possible to add ambient occlusion? DPFix for Deadly Premonition 1 contained this option.

**Comment by SuiMachine** [comment]
As I have stated on Twitter - the game already uses HBAO. It just isn't very strong (and what is really lacking, I'd say is global illumination, anyway and overall materials). I'll probably expose its settings in 0.7.0, but I will probably start taking it slower now, as I have been working on it pretty much non stop since last Sunday during my free time.
